### ISSUE TITLE
Fail to parse request body when there're query params guard

### ISSUE THREAD

**Issue by winterland1989** [philopon/apiary#17]
After some digging i final found how to reproduce this problem:
if you use `getReqBodyParams` inside a router with query params guard like this:
```.hs
commentRouter = do
    [capture|/comment|] $ do
        method POST . ([key|whatever|] =: pText) . action $ do
            params <- getReqBodyParams
            liftIO $ print params
```
you won't get any body params, a more interesting situation is like this:
```.hs
commentRouter ::  Monad m => ApiaryT '[Session T.Text IO, Persist, Logger] '[] IO m ()
commentRouter = do
    [capture|/comment|] $ do
        method POST . action $ do
            params <- getReqBodyParams
            liftIO $ print params

        method GET . ([key|sid|] =: pInt64) .
            ([key|page|] =: pInt) .
            ([key|perPage|] =: pInt) .
            action $ do
            (sid, page, perPage) <- [params|sid, page, perPage|]
            cmts <- runSql $ selectList [CommentSnippet ==. toSqlKey sid]
                [Asc CommentMtime, LimitTo perPage, OffsetBy $ (page - 1) * perPage]
            jsonRes cmts
  where
    pInt64 :: Proxy Int64
    pInt64 = Proxy
```
That's the code from my project, if i have a guarded router(the GET one above) inside the parent router, any other router(here is the POST one) can't get any params using `getReqBodyParams`.
I also tried `getRequest` and use `Network.Wai.Parse` to parse myself, but still can't get request body back, but if i remove the whole GET router, the POST router works as expected.

Is this a issue or just a usage problem?

**Comment by philopon** [comment]
Thanks for your report:smile:
I tried first code, but I don't reproduce it. (I don't check 2nd code yet, sorry)

code:

```.hs
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE DataKinds #-}

import Web.Apiary
import Control.Monad.Apiary.Action
import Network.Wai.Handler.Warp

main :: IO ()
main = runApiary (run 3000) def $ do
  commentRouter

commentRouter = do
    [capture|/comment|] $ do
        method POST . ([key|whatever|] =: pText) . action $ do
            params <- getReqBodyParams
            liftIO $ print params
```

request1:

```.sh
$ curl -XPOST -dtest=foo -dwhatever=bar localhost:3000/comment
```

stdout1:

```
[("test","foo"),("whatever","bar")]
```

request2:

```.sh
$ curl -XPOST -dtest=foo localhost:3000/comment
```

response2:

```
404 Page Notfound.
```

I think it is expected behaviour.
If you don't think so too, Please give me more information.

**Comment by winterland1989** [comment]
Thanks for testing, i can't reproduce the first one either, it must be a mistake, i test this one:
```haskell
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE DataKinds #-}

import Web.Apiary
import Control.Monad.Apiary.Action
import Network.Wai.Handler.Warp

main :: IO ()
main = runApiary (run 3000) def $ do
        [capture|/test|] $ do
            method POST . action $ do
                params <- getReqBodyParams
                liftIO $ print params

            method GET .
                ([key|page|] =: pInt) .
                ([key|perPage|] =: pInt) .
                action $ do
                (page, perPage) <- [params|page, perPage|]
                stop
```
with
`curl -XPOST -dtest=foo localhost:3000/test`
get respond:
`[]`

can you reproduce this one?

**Comment by philopon** [comment]
Thanks! My environment reproduced it.
It's seems bug of `getReqBodyParams`. I'm going to survey it.

**Comment by philopon** [comment]
Okey, I fixed it! please check [#17](../tree/%2317) branch.
If it fixed, I'll release v1.4.5.

**Comment by winterland1989** [comment]
ok,  testing right now.

**Comment by winterland1989** [comment]
The problem still exist, i think it's related where the request get parsed maybe?

**Comment by philopon** [comment]
Hmm... I tried [your code](#issuecomment-135597268).

```.sh
$ curl -XPOST -dtest=foo localhost:3000/test
```

returns

```
[("test","foo")]
```

Could you explain your situation more?

**Comment by winterland1989** [comment]
Sorry for a bad report due to build problem, after a clean rebuild, i can confirm this do fix the problem, thanks!

**Comment by philopon** [comment]
Don't worry:smile: I released v1.4.5.
Thanks for your bug reports!
